import * as THREE from "three";

export const ANIMATION_TYPES = {LOOP_ONCE: THREE.LoopOnce, INFINITY: THREE.LoopRepeat}
export const ANIMATION_TRIGGERS = {ON_SLIDE_CHANGE: "ON_SLIDE_CHANGE", ON_ANIMATION_END: "ON_ANIMATION_END"}